Repository Omkar-Sonawane-23/Maa-Vimala, pull requests merged in 2024-05, with the labels that each got.

#44 Added News Sections at the bottom #11
  index.html
  style.css
Labels: GSSOC24

#102 Issue fixed #33 improved UI
  index.html
  script.js
  style.css
Labels: GSSOC24, Level 3

#103 added favicon
  assets/favicon.png
  index.html
Labels: GSSOC24, Level 1

#104 Removed unnecessary commented code and added comments
  index.html
  script.js
  style.css
Labels: GSSOC24, Level 1

#70 Updated Readme
  README.md
Labels: GSSOC24, Level 1

#110 Repository Link Updation and matched color pallete
  index.html
  style.css
Labels: GSSOC24, Level 1

#118 Added auto-suggestion of search for search experience enhancement.
  autocomplete.js
  index.html
  style.css
Labels: GSSOC24, Level 2

#119 issue #59 solved
  index.html
  style.css
Labels: GSSOC24, Level 1

#120 Icon Shifted (solved: issue#82)
  index.html
  style.css
Labels: GSSOC24, Level 1

#212 Added Logo
  .vscode/settings.json
  MAA-VIMALAlogo.png
  index.html
  style.css
Labels: GSSOC24, level1

#226 NavBar Added
  index.html
  style.css
Labels: GSSOC24, level2

#231 Update Time and date
  script.js
Labels: GSSOC24, level2
